# Generated by Django 4.2.8 on 2024-01-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_guests_int',
            new_name='number_of_guests',
        ),
    ]
