# Generated by Django 4.2.8 on 2024-01-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_number_of_guests_int_reservation_number_of_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=2)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'time_slot']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '16:00'), (2, '16:30'), (3, '17:00'), (4, '17:30'), (5, '18:00'), (6, '18:30'), (7, '19:00'), (8, '19:30'), (9, '20:00'), (10, '20:30')], default=2),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
