# Generated by Django 4.2.8 on 2024-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
