# Generated by Django 4.2.8 on 2024-01-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_customer_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['capacity']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_number',
        ),
        migrations.AddField(
            model_name='table',
            name='number_of_tables',
            field=models.IntegerField(default=4),
        ),
    ]
