# Generated by Django 4.2.8 on 2024-01-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_table_options_remove_table_table_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='table_number',
            new_name='table',
        ),
    ]
