# Generated by Django 4.2.13 on 2024-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_remove_customer_owner_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
